this["JST"] = this["JST"] || {};

this["JST"]["set_password"] = function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (message, minLen, result) {
buf.push("<div id=\"user-passwd-dialog\" class=\"modal\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header bg-warning\"><button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">&times;</span></button><h4 class=\"modal-title\"><span class=\"glyphicon glyphicon-log-in\"></span><span> Set User Password</span></h4></div><div class=\"modal-body\">");
if ( message.length > 0)
{
buf.push("<!-- show any messages that come back with authentication--><div class=\"alert alert-info\">" + (jade.escape((jade_interp = message) == null ? '' : jade_interp)) + "</div>");
}
buf.push("<!-- LOGIN FORM--><form><div class=\"form-group\"><label for=\"user-password\">Password</label><input id=\"user-password\" type=\"password\" placeholder=\"New Password\" class=\"form-control\"/></div><div class=\"form-group\"><label for=\"user-confirm\">Confirm Password</label><input id=\"user-confirm\" type=\"password\" disabled=\"disabled\" placeholder=\"Confirm Password\" class=\"form-control\"/></div></form></div><div class=\"modal-footer\"><button id=\"user-change-password\" type=\"button\" disabled=\"disabled\" class=\"btn btn-warning btn-lg\">Change Password</button><button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-warning btn-lg\">Cancel</button></div></div></div></div><script type=\"text/javascript\">function checkPasswordMatch() {\n    var password = $(\"#user-password\").val();\n    var confirmPassword = $(\"#user-confirm\").val();\n\n    if (password !== confirmPassword) {\n        //$(\"#user-confirm\").css(\"background\", \"red\");\n        $(\"#user-confirm\").removeClass(\"alert alert-success\").addClass(\"alert alert-danger\");\n        $(\"#user-change-password\").prop(\"disabled\", true);\n        return false;\n    } else {\n        //$(\"#user-confirm\").css(\"background\", \"green\");\n        $(\"#user-confirm\").removeClass(\"alert alert-danger\").addClass(\"alert alert-success\");\n        $(\"#user-change-password\").prop(\"disabled\", false);\n        return true;\n    }\n}\n$(\"#user-password\").keyup(function() {\n    var password = $(\"#user-password\").val();\n    if (password.length >= " + (jade.escape((jade_interp =  minLen ) == null ? '' : jade_interp)) + ") {\n        $(\"#user-confirm\").prop(\"disabled\", false);\n        checkPasswordMatch();\n    } else { \n        $(\"#user-confirm\").prop(\"disabled\", true);\n    }\n});\n$(\"#user-confirm\").keyup(function() {\n    var password = $(\"#user-password\").val();\n    if (password.length >= " + (jade.escape((jade_interp =  minLen ) == null ? '' : jade_interp)) + ") {\n        checkPasswordMatch();\n    }\n});\n$(\"#user-change-password\").click(function() {\n    var password = $(\"#user-password\").val();\n    " + (jade.escape((jade_interp = result) == null ? '' : jade_interp)) + "(password);\n    $('#user-passwd-dialog').modal('hide');\n});</script>");}.call(this,"message" in locals_for_with?locals_for_with.message:typeof message!=="undefined"?message:undefined,"minLen" in locals_for_with?locals_for_with.minLen:typeof minLen!=="undefined"?minLen:undefined,"result" in locals_for_with?locals_for_with.result:typeof result!=="undefined"?result:undefined));;return buf.join("");
};