this["Templates"] = this["Templates"] || {};

this["Templates"]["set_password"] = function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (message, minLen, parent) {
var jade_indent = [];
buf.push("\n<div id=\"user-passwd-dialog\" class=\"modal\">\n  <div class=\"modal-dialog\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header bg-warning\">\n        <button type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\" class=\"close\"><span aria-hidden=\"true\">&times;</span></button>\n        <h4 class=\"modal-title\"><span class=\"glyphicon glyphicon-log-in\"></span><span> Set User Password</span></h4>\n      </div>\n      <div class=\"modal-body\">");
if ( message.length > 0)
{
buf.push("\n        <!-- show any messages that come back with authentication-->\n        <div class=\"alert alert-info\">" + (jade.escape((jade_interp = message) == null ? '' : jade_interp)) + "</div>");
}
buf.push("\n        <!-- LOGIN FORM-->\n        <form>\n          <div class=\"form-group\">\n            <label for=\"user-password\">Password</label>\n            <input id=\"user-password\" type=\"password\" placeholder=\"New Password\" class=\"form-control\"/>\n          </div>\n          <div class=\"form-group\">\n            <label for=\"user-confirm\">Confirm Password</label>\n            <input id=\"user-confirm\" type=\"password\" disabled=\"disabled\" placeholder=\"Confirm Password\" class=\"form-control\"/>\n          </div>\n        </form>\n      </div>\n      <div class=\"modal-footer\">\n        <button id=\"user-change-password\" type=\"button\" disabled=\"disabled\" class=\"btn btn-warning btn-lg\">Change Password</button>\n        <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-warning btn-lg\">Cancel</button>\n      </div>\n    </div>\n  </div>\n</div>\n<script type=\"text/javascript\">\n  function checkMatch() {\n      var password = $(\"#user-password\").val();\n      var confirmPassword = $(\"#user-confirm\").val();\n  \n      if (password !== confirmPassword) {\n          $(\"#user-confirm\").removeClass(\"alert alert-success\").addClass(\"alert alert-danger\");\n          $(\"#user-change-password\").prop(\"disabled\", true);\n          return false;\n      } else {\n          $(\"#user-confirm\").removeClass(\"alert alert-danger\").addClass(\"alert alert-success\");\n          $(\"#user-change-password\").prop(\"disabled\", false);\n          return true;\n      }\n  }\n  $(\"#user-password\").keyup(function() {\n      var password = $(\"#user-password\").val();\n      if (password.length >= " + (jade.escape((jade_interp =  minLen ) == null ? '' : jade_interp)) + ") {\n          $(\"#user-confirm\").prop(\"disabled\", false);\n          checkMatch();\n      } else { \n          $(\"#user-confirm\").prop(\"disabled\", true);\n      }\n  });\n  $(\"#user-confirm\").keyup(function() {\n      var password = $(\"#user-password\").val();\n      if (password.length >= " + (jade.escape((jade_interp =  minLen ) == null ? '' : jade_interp)) + ") {\n          checkMatch();\n      }\n  });\n  $(\"#user-change-password\").click(function() {\n      var password = $(\"#user-password\").val();\n      $(\"#" + (jade.escape((jade_interp =  parent ) == null ? '' : jade_interp)) + "\").data(\"onChange\")(password);\n      $('#user-passwd-dialog').modal('hide');\n  });\n</script>");}.call(this,"message" in locals_for_with?locals_for_with.message:typeof message!=="undefined"?message:undefined,"minLen" in locals_for_with?locals_for_with.minLen:typeof minLen!=="undefined"?minLen:undefined,"parent" in locals_for_with?locals_for_with.parent:typeof parent!=="undefined"?parent:undefined));;return buf.join("");
};